import { StudentFormConfig } from "@/types";

export const EXTRACTED_ADMISSION_FIELDS: StudentFormConfig[] = [
    // 1. Admission Details
    // admissionNumber is the PRIMARY student ID — shown in the students list, fees, ID cards & QR codes.
    // Always placed first so school staff can see and directly edit it.
    { fieldName: 'admissionNumber', label: 'Admission Number', visible: true, required: true, sectionName: 'Admission Details', hasAutoManualToggle: true, orderIndex: -1 },
    { fieldName: 'registrationNo', label: 'Registration Number', visible: true, required: false, sectionName: 'Admission Details', hasAutoManualToggle: true, orderIndex: 0 },
    { fieldName: 'enrollmentNo', label: 'Enrollment Number', visible: true, required: false, sectionName: 'Admission Details', hasAutoManualToggle: true, orderIndex: 1 },
    { fieldName: 'apaarId', label: 'APAAR ID', visible: true, required: false, sectionName: 'Admission Details', hasAutoManualToggle: true, orderIndex: 2 },
    { fieldName: 'penNo', label: 'PEN No.', visible: true, required: false, sectionName: 'Admission Details', hasAutoManualToggle: true, orderIndex: 3 },
    { fieldName: 'srNo', label: 'SR No.', visible: true, required: false, sectionName: 'Admission Details', hasAutoManualToggle: true, orderIndex: 4 },
    { fieldName: 'generalRegistrationNo', label: 'General Registration No.', visible: true, required: false, sectionName: 'Admission Details', hasAutoManualToggle: true, orderIndex: 5 },
    { fieldName: 'admissionDate', label: 'Admission Date', visible: true, required: true, sectionName: 'Admission Details', fieldType: 'date', orderIndex: 6 },
    { fieldName: 'stream', label: 'Stream', visible: true, required: false, sectionName: 'Admission Details', fieldType: 'select', options: ['Science', 'Commerce', 'Arts'], orderIndex: 7 },
    { fieldName: 'classAppliedFor', label: 'Class (Applied For)', visible: true, required: true, sectionName: 'Admission Details', fieldType: 'select', orderIndex: 8 },
    { fieldName: 'enrolledYear', label: 'Enrolled Year', visible: true, required: true, sectionName: 'Admission Details', orderIndex: 9 },
    { fieldName: 'enrolledSession', label: 'Enrolled Session', visible: true, required: true, sectionName: 'Admission Details', orderIndex: 10 },
    { fieldName: 'className', label: 'Enrolled Class', visible: true, required: true, sectionName: 'Admission Details', fieldType: 'select', orderIndex: 11 },
    { fieldName: 'section', label: 'Enrolled Section', visible: true, required: true, sectionName: 'Admission Details', fieldType: 'select', orderIndex: 12 },
    { fieldName: 'rollNumber', label: 'Roll Number', visible: true, required: false, sectionName: 'Admission Details', hasAutoManualToggle: true, orderIndex: 13 },
    { fieldName: 'house', label: 'House', visible: true, required: false, sectionName: 'Admission Details', fieldType: 'select', options: ['Red', 'Blue', 'Green', 'Yellow', 'N/A'], orderIndex: 14 },
    { fieldName: 'rte', label: 'Is RTE Student?', visible: true, required: false, sectionName: 'Admission Details', fieldType: 'select', options: ['No', 'Yes'], orderIndex: 15 },
    { fieldName: 'studentType', label: 'Student Type', visible: true, required: false, sectionName: 'Admission Details', fieldType: 'select', options: ['New', 'Old'], orderIndex: 16 },
    { fieldName: 'photo', label: 'Student Photo', visible: true, required: false, sectionName: 'Admission Details', orderIndex: 17 },
    { fieldName: 'firstLanguage', label: '1st Language', visible: true, required: true, sectionName: 'Admission Details', fieldType: 'select', options: ['English', 'Hindi', 'Sanskrit', 'Urdu', 'Other'], orderIndex: 18 },
    { fieldName: 'secondLanguage', label: '2nd Language', visible: true, required: true, sectionName: 'Admission Details', fieldType: 'select', options: ['English', 'Hindi', 'Sanskrit', 'Urdu', 'Other'], orderIndex: 19 },
    { fieldName: 'thirdLanguage', label: '3rd Language', visible: true, required: true, sectionName: 'Admission Details', fieldType: 'select', options: ['English', 'Hindi', 'Sanskrit', 'Urdu', 'Other'], orderIndex: 20 },
    { fieldName: 'referredBy', label: 'Referred By', visible: true, required: false, sectionName: 'Admission Details', orderIndex: 21 },
    { fieldName: 'sibling', label: 'Sibling Details', visible: true, required: false, sectionName: 'Admission Details', orderIndex: 21.5 },

    // 2. Personal Information
    { fieldName: 'firstName', label: 'First Name', visible: true, required: true, sectionName: 'Personal Information', orderIndex: 22 },
    { fieldName: 'lastName', label: 'Last Name', visible: true, required: true, sectionName: 'Personal Information', orderIndex: 23 },
    { fieldName: 'dob', label: 'Date of Birth', visible: true, required: true, sectionName: 'Personal Information', fieldType: 'date', orderIndex: 24 },
    { fieldName: 'gender', label: 'Gender', visible: true, required: true, sectionName: 'Personal Information', fieldType: 'select', options: ['Male', 'Female', 'Other'], orderIndex: 25 },
    { fieldName: 'bloodGroup', label: 'Blood Group', visible: true, required: false, sectionName: 'Personal Information', fieldType: 'select', options: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'], orderIndex: 26 },
    { fieldName: 'religion', label: 'Religion', visible: true, required: false, sectionName: 'Personal Information', fieldType: 'select', options: ['Hinduism', 'Islam', 'Christianity', 'Sikhism', 'Buddhism', 'Jainism', 'Other'], orderIndex: 27 },
    { fieldName: 'category', label: 'Category', visible: true, required: false, sectionName: 'Personal Information', fieldType: 'select', options: ['General', 'OBC', 'SC', 'ST', 'EWS'], orderIndex: 28 },
    { fieldName: 'phone', label: 'Mobile Number', visible: true, required: true, sectionName: 'Personal Information', orderIndex: 29 },
    { fieldName: 'email', label: 'Email ID', visible: true, required: false, sectionName: 'Personal Information', orderIndex: 30 },
    { fieldName: 'whatsappNo', label: 'WhatsApp Number', visible: true, required: false, sectionName: 'Personal Information', orderIndex: 31 },
    { fieldName: 'alternateNumber', label: 'Alternate Number', visible: true, required: false, sectionName: 'Personal Information', orderIndex: 32 },
    { fieldName: 'height', label: 'Height (cm)', visible: true, required: false, sectionName: 'Personal Information', orderIndex: 33 },
    { fieldName: 'weight', label: 'Weight (kg)', visible: true, required: false, sectionName: 'Personal Information', orderIndex: 34 },
    { fieldName: 'measurementDate', label: 'Record Date (Height/Weight)', visible: true, required: false, sectionName: 'Personal Information', fieldType: 'date', orderIndex: 35 },
    { fieldName: 'specialNeeds', label: 'Special Needs / Disability', visible: true, required: false, sectionName: 'Personal Information', fieldType: 'select', options: ['No', 'Yes'], orderIndex: 36 },
    { fieldName: 'specialNeedsDetails', label: 'Special Needs Details', visible: true, required: false, sectionName: 'Personal Information', dependsOn: { fieldName: 'specialNeeds', value: 'Yes' }, orderIndex: 37 },

    // 3. Parent Information
    { fieldName: 'fatherName', label: "Father's Name", visible: true, required: true, sectionName: 'Parents/Guardian Details', orderIndex: 38 },
    { fieldName: 'fatherOccupation', label: "Father's Occupation", visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 39 },
    { fieldName: 'fatherPhone', label: "Father's Mobile No.", visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 40 },
    { fieldName: 'fatherPhoto', label: "Father's Photo", visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 41 },
    { fieldName: 'fatherDocName', label: "Father Document Name", visible: true, required: false, placeholder: 'e.g. Aadhar Card', sectionName: 'Parents/Guardian Details', orderIndex: 42 },
    { fieldName: 'fatherDocFile', label: "Father Document Upload", visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 43 },
    { fieldName: 'motherName', label: "Mother's Name", visible: true, required: true, sectionName: 'Parents/Guardian Details', orderIndex: 44 },
    { fieldName: 'motherOccupation', label: "Mother's Occupation", visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 45 },
    { fieldName: 'motherPhone', label: "Mother's Mobile No.", visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 46 },
    { fieldName: 'motherPhoto', label: "Mother's Photo", visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 47 },
    { fieldName: 'motherDocName', label: "Mother Document Name", visible: true, required: false, placeholder: 'e.g. PAN Card', sectionName: 'Parents/Guardian Details', orderIndex: 48 },
    { fieldName: 'motherDocFile', label: "Mother Document Upload", visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 49 },
    { fieldName: 'guardianSelection', label: 'Guardian Selection', visible: true, required: true, sectionName: 'Parents/Guardian Details', orderIndex: 50 },
    { fieldName: 'guardianName', label: 'Guardian Name', visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 51 },
    { fieldName: 'guardianRelation', label: 'Guardian Relation', visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 52 },
    { fieldName: 'guardianOccupation', label: 'Guardian Occupation', visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 53 },
    { fieldName: 'guardianPhone', label: 'Guardian Mobile No.', visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 54 },
    { fieldName: 'guardianPhoto', label: 'Guardian Photo', visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 55 },
    { fieldName: 'guardianAddress', label: 'Guardian Address', visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 56 },
    { fieldName: 'guardianEmail', label: 'Guardian Email', visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 57 },
    { fieldName: 'guardianDocName', label: 'Guardian Document Name', visible: true, required: false, placeholder: 'e.g. ID Proof', sectionName: 'Parents/Guardian Details', orderIndex: 58 },
    { fieldName: 'guardianDocFile', label: 'Guardian Document Upload', visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 59 },
    { fieldName: 'fatherEmail', label: "Father's Email ID", visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 60 },
    { fieldName: 'motherEmail', label: "Mother's Email ID", visible: true, required: false, sectionName: 'Parents/Guardian Details', orderIndex: 61 },

    // 4. Address Details
    { fieldName: 'currentAddress', label: 'Address Line 1', visible: true, required: true, placeholder: 'Enter address line 1', sectionName: 'Address Details', orderIndex: 62 },
    { fieldName: 'village', label: 'Village', visible: true, required: false, placeholder: 'Enter village', sectionName: 'Address Details', orderIndex: 63 },
    { fieldName: 'locality', label: 'Locality', visible: true, required: false, placeholder: 'Enter locality', sectionName: 'Address Details', orderIndex: 64 },
    { fieldName: 'postOffice', label: 'P.O (Post Office)', visible: true, required: false, placeholder: 'Enter post office', sectionName: 'Address Details', orderIndex: 65 },
    { fieldName: 'policeStation', label: 'P.S (Police Station)', visible: true, required: false, placeholder: 'Enter police station', sectionName: 'Address Details', orderIndex: 66 },
    { fieldName: 'city', label: 'City', visible: true, required: false, placeholder: 'Enter current city', sectionName: 'Address Details', orderIndex: 67 },
    { fieldName: 'district', label: 'District', visible: true, required: false, placeholder: 'Enter district', sectionName: 'Address Details', orderIndex: 68 },
    { fieldName: 'state', label: 'Current State', visible: true, required: false, placeholder: 'Enter current state', sectionName: 'Address Details', orderIndex: 69 },
    { fieldName: 'pincode', label: 'Current PIN', visible: true, required: false, placeholder: 'Enter current PIN', sectionName: 'Address Details', orderIndex: 70 },
    { fieldName: 'country', label: 'Country', visible: true, required: false, placeholder: 'Enter country', sectionName: 'Address Details', orderIndex: 71 },
    { fieldName: 'permanentAddress', label: 'Permanent Address', visible: true, required: false, sectionName: 'Address Details', orderIndex: 72 },
    { fieldName: 'permanentVillage', label: 'Permanent Village', visible: true, required: false, sectionName: 'Address Details', orderIndex: 73 },
    { fieldName: 'permanentLocality', label: 'Permanent Locality', visible: true, required: false, sectionName: 'Address Details', orderIndex: 74 },
    { fieldName: 'permanentPostOffice', label: 'Permanent P.O (Post Office)', visible: true, required: false, sectionName: 'Address Details', orderIndex: 75 },
    { fieldName: 'permanentPoliceStation', label: 'Permanent P.S (Police Station)', visible: true, required: false, sectionName: 'Address Details', orderIndex: 76 },
    { fieldName: 'permanentDistrict', label: 'Permanent District', visible: true, required: false, sectionName: 'Address Details', orderIndex: 77 },
    { fieldName: 'permanentCity', label: 'Permanent City', visible: true, required: false, sectionName: 'Address Details', orderIndex: 78 },
    { fieldName: 'permanentState', label: 'Permanent State', visible: true, required: false, sectionName: 'Address Details', orderIndex: 79 },
    { fieldName: 'permanentPincode', label: 'Permanent Pincode', visible: true, required: false, sectionName: 'Address Details', orderIndex: 80 },
    { fieldName: 'permanentCountry', label: 'Permanent Country', visible: true, required: false, sectionName: 'Address Details', orderIndex: 81 },

    // 5. Previous Academic Details
    { fieldName: 'previousSchool', label: 'Last School Name', visible: true, required: false, sectionName: 'Previous Academic Details', orderIndex: 82 },
    { fieldName: 'previousLastClass', label: "Previous School's Last Class", visible: true, required: false, sectionName: 'Previous Academic Details', orderIndex: 83 },
    { fieldName: 'affiliatedBoard', label: 'Affiliated Board', visible: true, required: false, sectionName: 'Previous Academic Details', orderIndex: 84 },
    { fieldName: 'marksObtained', label: 'Marks Obtained', visible: true, required: false, sectionName: 'Previous Academic Details', orderIndex: 85 },
    { fieldName: 'percentageCGPA', label: 'Percentage / CGPA', visible: true, required: false, sectionName: 'Previous Academic Details', orderIndex: 86 },
    { fieldName: 'result', label: 'Result', visible: true, required: false, sectionName: 'Previous Academic Details', orderIndex: 87 },
    { fieldName: 'tcDate', label: 'TC Date', visible: true, required: false, sectionName: 'Previous Academic Details', orderIndex: 88 },
    { fieldName: 'tcNo', label: 'TC Number', visible: true, required: false, sectionName: 'Previous Academic Details', orderIndex: 89 },
    { fieldName: 'tcFile', label: 'upload TC File', visible: true, required: false, sectionName: 'Previous Academic Details', orderIndex: 90 },

    // 6. Bank & Govt IDs
    { fieldName: 'aadhaarNo', label: 'Aadhar Number', visible: true, required: false, sectionName: 'Bank & Govt IDs', orderIndex: 91 },
    { fieldName: 'samagraId', label: 'Samagra ID', visible: true, required: false, sectionName: 'Bank & Govt IDs', orderIndex: 92 },
    { fieldName: 'bankAccountNo', label: 'Bank Account No.', visible: true, required: false, sectionName: 'Bank & Govt IDs', orderIndex: 93 },
    { fieldName: 'ifscCode', label: 'IFSC Code', visible: true, required: false, sectionName: 'Bank & Govt IDs', orderIndex: 94 },
    { fieldName: 'bankName', label: 'Bank Name', visible: true, required: false, sectionName: 'Bank & Govt IDs', orderIndex: 95 },
    { fieldName: 'accountHolderName', label: 'Account Holder', visible: true, required: false, sectionName: 'Bank & Govt IDs', orderIndex: 96 },

    // 7. Miscellaneous
    { fieldName: 'caste', label: 'Caste', visible: true, required: false, sectionName: 'Miscellaneous', orderIndex: 97 },
    { fieldName: 'nationality', label: 'Nationality', visible: true, required: false, sectionName: 'Miscellaneous', orderIndex: 98 },

    // 8. Miscellaneous Documents
    { fieldName: 'miscDocuments', label: 'Misc. Documents Upload', visible: true, required: false, sectionName: 'Miscellaneous Documents', orderIndex: 99 },
];
